name: Build Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: linux-x64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: darwin-x64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: darwin-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Build binary
        run: |
          npx cargo-cp-artifact -a cdylib dtln-rs index.node -- \
            cargo build -p dtln-rs --lib --release \
            --target ${{ matrix.target }}
          cp dtln.node.js dtln.js

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}
          path: |
            index.node
            dtln.js

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: prebuilt/

      - name: List artifacts
        run: ls -R prebuilt/

      - name: Create package
        run: npm pack

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: npm-package
          path: dtln-rs-*.tgz

      - name: Publish to npm (if tagged)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish --access public
